name: Prerelease
on:
  push:
    tags-ignore:
      - '**'
    branches-ignore:
      - 'dependabot/**'
    paths:
      - .babelrc.js
      - .eslintrc.js
      - .flowconfig
      - .github/workflows/prerelease.yml
      - .yarn/versions/*
      - .yarnrc.yml
      - README.md
      - bin/**/*
      - package.json
      - prettier.config.js
      - src/**/*
      - test/**/*
      - tsconfig.json
      - yarn.lock
jobs:
  prerelease:
    name: Publish Prerelease
    uses: CumulusDS/workflows/.github/workflows/package-prerelease.yml@master
    secrets: inherit
